{{- if .Values.objectStorage.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.objectStorage.secretName | quote }}
  labels:
    app.kubernetes.io/name: mlflow-secrets
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  access-key-id: {{ required "objectStorage.accessKeyId is required" .Values.objectStorage.accessKeyId | quote }}
  secret-access-key: {{ required "objectStorage.secretAccessKey is required" .Values.objectStorage.secretAccessKey | quote }}
  endpoint-url: {{ required "objectStorage.endpointUrl is required" .Values.objectStorage.endpointUrl | quote }}
{{- end }}