{{- if .Values.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oidc.secretName | quote }}
  labels:
    app.kubernetes.io/name: mlflow-secrets
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  client-id: {{ required "oidc.clientId is required" .Values.oidc.clientId | quote }}
  client-secret: {{ required "oidc.clientSecret is required" .Values.oidc.clientSecret | quote }}
  secret-key: {{ required "oidc.secretKey is required" .Values.oidc.secretKey | quote }}
{{- end }}