apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-postgres"
  labels:
    app: "{{ .Release.Name }}-postgres"
spec:
  clusterIP: None
  ports:
    - name: postgres
      port: {{ default 5432 .Values.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    app: "{{ .Release.Name }}-postgres"
