apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "{{ .Release.Name }}-postgres"
  labels:
    app: "{{ .Release.Name }}-postgres"
stringData:
  sqlalchemy-uri: {{ printf "postgresql://%s:%s@%s:%v/%s" (.Values.postgres.user | urlquery) (.Values.postgres.password | urlquery) .Values.postgres.host .Values.service.port .Values.postgres.database | quote }}
  oidc-uri: {{ printf "postgresql://%s:%s@%s:%v/%s" (.Values.postgres.user | urlquery) (.Values.postgres.password | urlquery) .Values.postgres.host .Values.service.port .Values.postgres.authDatabase | quote }}
  
  
  # # NOTE: data must be base64-encoded. Helm will do this via b64enc.
  # postgres-user: {{ required "values.postgres.user is required" .Values.postgres.user | b64enc | quote }}
  # postgres-password: {{ required "values.postgres.password is required" .Values.postgres.password | b64enc | quote }}
  # postgres-db: {{ required "values.postgres.database is required" .Values.postgres.database | b64enc | quote }}
